name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "!src/blog/drafts/**"
      - ".eleventy.js"
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
      - name: Install dependencies
        uses: ./.github/workflows/actions/install-dependencies
      - name: Restore Eleventy Fetch cache
        uses: actions/cache/restore@v4
        id: eleventy-fetch-cache
        with:
          path: .cache
          key: eleventy-fetch-cache
      - name: Build Eleventy
        run: npm run build
      - name: Save Eleventy Fetch cache
        uses: actions/cache/save@v4
        with:
          path: .cache
          key: ${{ steps.eleventy-fetch-cache.outputs.cache-primary-key }}
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: beeps-website
          path: _site
          retention-days: 1
  deploy:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: beeps-website
      - name: Upload files
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
          TARGET: ${{ secrets.SSH_PATH }}
          ARGS: -avP --compress --delete-after --human-readable
